// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DMAutoTests
{
	[Table("BLAST_HOLE")]
	public class BlastHole
	{
		[Column("ID"                                                                                            )] public int?    Id                       { get; set; } // int
		[Column("BLAST_BLOCK_ID"             , IsPrimaryKey = true , PrimaryKeyOrder = 1                        )] public int     BlastBlockId             { get; set; } // int
		[Column("NAME"                       , CanBeNull    = false, IsPrimaryKey    = true, PrimaryKeyOrder = 0)] public string  Name                     { get; set; } = null!; // nvarchar(32)
		[Column("DESIGN_CHARGE_MASS"                                                                            )] public double? DesignChargeMass         { get; set; } // float
		[Column("DESIGN_CHARGE_HEIGHT"                                                                          )] public double? DesignChargeHeight       { get; set; } // float
		[Column("DESIGN_EXPLOSIVE_ID"                                                                           )] public int?    DesignExplosiveId        { get; set; } // int
		[Column("REAL_CHARGE_MASS"                                                                              )] public double? RealChargeMass           { get; set; } // float
		[Column("REAL_CHARGE_HEIGHT"                                                                            )] public double? RealChargeHeight         { get; set; } // float
		[Column("REAL_EXPLOSIVE_ID"                                                                             )] public int?    RealExplosiveId          { get; set; } // int
		[Column("HOLE_STATUS_ID"                                                                                )] public int?    HoleStatusId             { get; set; } // int
		[Column("HOLE_DEPTH"                                                                                    )] public double? HoleDepth                { get; set; } // float
		[Column("HOLE_TAMPING"                                                                                  )] public double? HoleTamping              { get; set; } // float
		[Column("HOLE_DIAMETER"                                                                                 )] public double? HoleDiameter             { get; set; } // float
		[Column("X"                                                                                             )] public double? X                        { get; set; } // float
		[Column("Y"                                                                                             )] public double? Y                        { get; set; } // float
		[Column("Z"                                                                                             )] public double? Z                        { get; set; } // float
		[Column("ACTIVE"                                                                                        )] public bool?   Active                   { get; set; } // bit
		[Column("ADDCHRG_STAFF_ID"                                                                              )] public int?    AddchrgStaffId           { get; set; } // int
		[Column("REAL_ADDITIONAL_CHARGE_MASS"                                                                   )] public double? RealAdditionalChargeMass { get; set; } // float
		[Column("ADDITIONAL_CHARGE_MASS"                                                                        )] public double? AdditionalChargeMass     { get; set; } // float
		[Column("ADJACENT_CHARGE"                                                                               )] public double? AdjacentCharge           { get; set; } // float
		[Column("RESIDUAL_CHARGE"                                                                               )] public double? ResidualCharge           { get; set; } // float
		[Column("AREA_ID"                                                                                       )] public int?    AreaId                   { get; set; } // int
		[Column("GGD1"                                                                                          )] public int?    Ggd1                     { get; set; } // int
		[Column("GGD2"                                                                                          )] public int?    Ggd2                     { get; set; } // int
		[Column("EM_MASS"                                                                                       )] public int?    EmMass                   { get; set; } // int
		[Column("AS_MASS"                                                                                       )] public int?    AsMass                   { get; set; } // int
		[Column("GGD_MASS"                                                                                      )] public int?    GgdMass                  { get; set; } // int
		[Column("WATER_MASS"                                                                                    )] public int?    WaterMass                { get; set; } // int
		[Column("HOSE_UNWINDING"                                                                                )] public bool?   HoseUnwinding            { get; set; } // bit
	}
}
