// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DMAutoTests
{
	[Table("BLAST_BLOCK")]
	public class BlastBlock
	{
		[Column("ID"           , IsPrimaryKey = true)] public int       Id           { get; set; } // int
		[Column("NAME"                              )] public string?   Name         { get; set; } // nvarchar(32)
		[Column("LOCATION_ID"                       )] public int?      LocationId   { get; set; } // int
		[Column("ACTIVE"                            )] public bool?     Active       { get; set; } // bit
		[Column("AREA_ID"                           )] public int?      AreaId       { get; set; } // int
		[Column("BLOCK_BLASTED"                     )] public DateTime? BlockBlasted { get; set; } // datetime
	}
}
