// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DMAutoTests
{
	[Table("BLAST_CARD_CONTAIN")]
	public class BlastCardContain
	{
		[Column("NUMBER"          )] public int?    Number         { get; set; } // int
		[Column("CARD_ID"         )] public int     CardId         { get; set; } // int
		[Column("BLOCK_NAME"      )] public string? BlockName      { get; set; } // nvarchar(32)
		[Column("HOLE_NAME"       )] public string? HoleName       { get; set; } // nvarchar(32)
		[Column("HOLE_DEPTH"      )] public string? HoleDepth      { get; set; } // nvarchar(32)
		[Column("HOLE_DESIGN_MASS")] public string? HoleDesignMass { get; set; } // nvarchar(32)
		[Column("CHARGE_MASS"     )] public string? ChargeMass     { get; set; } // nvarchar(32)
	}
}
