// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DMAutoTests
{
	[Table("BLAST_ZONE_POINT")]
	public class BlastZonePoint
	{
		[Column("BLAST_ZONE_ID"                                                                     )] public int?    BlastZoneId   { get; set; } // int
		[Column("BLAST_ZONE_GUID", CanBeNull    = false, IsPrimaryKey    = true, PrimaryKeyOrder = 0)] public string  BlastZoneGuid { get; set; } = null!; // nvarchar(64)
		[Column("SEQUENCE"       , IsPrimaryKey = true , PrimaryKeyOrder = 1                        )] public int     Sequence      { get; set; } // int
		[Column("X"                                                                                 )] public double? X             { get; set; } // float
		[Column("Y"                                                                                 )] public double? Y             { get; set; } // float
		[Column("Z"                                                                                 )] public double? Z             { get; set; } // float
	}
}
