// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DMAutoTests
{
	[Table("BLAST_CARD")]
	public class BlastCard
	{
		[Column("CARD_ID"              )] public int       CardId              { get; set; } // int
		[Column("BLOCK_ID"             )] public int       BlockId             { get; set; } // int
		[Column("BLOCK_NAME"           )] public string?   BlockName           { get; set; } // nvarchar(32)
		[Column("START_TIME"           )] public DateTime  StartTime           { get; set; } // datetime
		[Column("END_TIME"             )] public DateTime? EndTime             { get; set; } // datetime
		[Column("UNIT_ID"              )] public int       UnitId              { get; set; } // int
		[Column("PRIMARY_OPERATOR_ID"  )] public int?      PrimaryOperatorId   { get; set; } // int
		[Column("SECONDARY_OPERATOR_ID")] public int?      SecondaryOperatorId { get; set; } // int
		[Column("EXPLOSIVE_ID"         )] public int?      ExplosiveId         { get; set; } // int
		[Column("TOTAL_CHARGE_MASS"    )] public double?   TotalChargeMass     { get; set; } // float
	}
}
