// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DMAutoTests
{
	[Table("BLAST_ZONE_HOLES")]
	public class BlastZoneHole
	{
		[Column("AREA_ID"                               )] public int?   AreaId            { get; set; } // int
		[Column("BLAST_ZONE_ID"                         )] public int?   BlastZoneId       { get; set; } // int
		[Column("BLAST_ZONE_GUID"    , CanBeNull = false)] public string BlastZoneGuid     { get; set; } = null!; // nvarchar(64)
		[Column("BLAST_BLOCK_ID"                        )] public int?   BlastBlockId      { get; set; } // int
		[Column("BLAST_HOLE_NAME"    , CanBeNull = false)] public string BlastHoleName     { get; set; } = null!; // nvarchar(32)
		[Column("IS_START_HOLE"                         )] public bool   IsStartHole       { get; set; } // bit
		[Column("USE_ADJACENT_CHARGE"                   )] public bool   UseAdjacentCharge { get; set; } // bit
	}
}
