// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DMAutoTests
{
	[Table("CONSUMABLE_OPTIMAL")]
	public class ConsumableOptimal
	{
		[Column("ID"              , IsPrimaryKey = true)] public int     Id             { get; set; } // int
		[Column("CONS_ID"                              )] public int?    ConsId         { get; set; } // int
		[Column("RPM_MIN"                              )] public double? RpmMin         { get; set; } // float
		[Column("DIG_PRESSURE_MIN"                     )] public double? DigPressureMin { get; set; } // float
		[Column("AIR_PRESSURE_MIN"                     )] public double? AirPressureMin { get; set; } // float
		[Column("TORQUE_MIN"                           )] public double? TorqueMin      { get; set; } // float
		[Column("RPM_MAX"                              )] public double? RpmMax         { get; set; } // float
		[Column("DIG_PRESSURE_MAX"                     )] public double? DigPressureMax { get; set; } // float
		[Column("AIR_PRESSURE_MAX"                     )] public double? AirPressureMax { get; set; } // float
		[Column("TORQUE_MAX"                           )] public double? TorqueMax      { get; set; } // float
		[Column("AREA_ID"                              )] public int?    AreaId         { get; set; } // int
	}
}
