// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DMAutoTests
{
	[Table("CONSUMABLE")]
	public class Consumable
	{
		[Column("ID"                )] public int?      Id               { get; set; } // int
		[Column("NAME"              )] public string?   Name             { get; set; } // nvarchar(32)
		[Column("TYPE_ID"           )] public int?      TypeId           { get; set; } // int
		[Column("NUM_METERS_DRILLED")] public double?   NumMetersDrilled { get; set; } // float
		[Column("LIMIT"             )] public double?   Limit            { get; set; } // float
		[Column("ACTIVE"            )] public bool?     Active           { get; set; } // bit
		[Column("SERIAL_NUMBER"     )] public string?   SerialNumber     { get; set; } // nvarchar(32)
		[Column("ID_MANUFACTURER"   )] public int?      IdManufacturer   { get; set; } // int
		[Column("WRITE_OFF_DATE"    )] public DateTime? WriteOffDate     { get; set; } // datetime
		[Column("DRILL_BIT_DIAMETER")] public double?   DrillBitDiameter { get; set; } // float
		[Column("AREA_ID"           )] public int?      AreaId           { get; set; } // int
		[Column("ORDER_ID"          )] public int?      OrderId          { get; set; } // int
		[Column("START_METERS"      )] public double?   StartMeters      { get; set; } // float
	}
}
