// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DMAutoTests
{
	[Table("CONSUMABLE_VIOLATION")]
	public class ConsumableViolation
	{
		[Column("ID"          , IsPrimaryKey = true)] public int       Id          { get; set; } // int
		[Column("CONS_ID"                          )] public int?      ConsId      { get; set; } // int
		[Column("RPM"                              )] public double?   Rpm         { get; set; } // float
		[Column("DIG_PRESSURE"                     )] public double?   DigPressure { get; set; } // float
		[Column("AIR_PRESSURE"                     )] public double?   AirPressure { get; set; } // float
		[Column("TORQUE"                           )] public double?   Torque      { get; set; } // float
		[Column("DEPTH"                            )] public double?   Depth       { get; set; } // float
		[Column("HOLE_NAME"                        )] public string?   HoleName    { get; set; } // nvarchar(32)
		[Column("BLOCK_ID"                         )] public int?      BlockId     { get; set; } // int
		[Column("TIMESTAMP"                        )] public DateTime? Timestamp   { get; set; } // datetime
		[Column("AREA_ID"                          )] public int?      AreaId      { get; set; } // int
		[Column("UNIT_ID"                          )] public int?      UnitId      { get; set; } // int
	}
}
