// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DMAutoTests
{
	[Table("COORDS_MATH_RESULT")]
	public class CoordsMathResult
	{
		[Column("AREA_ID"                     , IsPrimaryKey = true)] public int     AreaId                     { get; set; } // int
		[Column("ROTATION_MATRIX_ID"                               )] public int?    RotationMatrixId           { get; set; } // int
		[Column("DISPLACEMENT_MATRIX_ID"                           )] public int?    DisplacementMatrixId       { get; set; } // int
		[Column("ERROR_MATRIX_ID"                                  )] public int?    ErrorMatrixId              { get; set; } // int
		[Column("SCALE_FACTOR"                                     )] public double? ScaleFactor                { get; set; } // float
		[Column("COMMON_TRANSFORMATION_ERROR"                      )] public double? CommonTransformationError  { get; set; } // float
		[Column("AVERAGE_TRANSFORMATION_ERROR"                     )] public double? AverageTransformationError { get; set; } // float
	}
}
