// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DMAutoTests
{
	[Table("COORDS_MATH_TRANSFORMATION")]
	public class CoordsMathTransformation
	{
		[Column("AREA_ID"      , IsPrimaryKey = true, PrimaryKeyOrder = 0)] public int     AreaId      { get; set; } // int
		[Column("SEQUENCE"     , IsPrimaryKey = true, PrimaryKeyOrder = 1)] public int     Sequence    { get; set; } // int
		[Column("POINT_LAT"                                              )] public double? PointLat    { get; set; } // float
		[Column("POINT_LNG"                                              )] public double? PointLng    { get; set; } // float
		[Column("POINT_ALT"                                              )] public double? PointAlt    { get; set; } // float
		[Column("POINT_LOCAL_X"                                          )] public double? PointLocalX { get; set; } // float
		[Column("POINT_LOCAL_Y"                                          )] public double? PointLocalY { get; set; } // float
		[Column("POINT_LOCAL_Z"                                          )] public double? PointLocalZ { get; set; } // float
	}
}
