// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DMAutoTests
{
	[Table("COORDS_PROJ_TRANSFORMATION")]
	public class CoordsProjTransformation
	{
		[Column("AREA_ID"               , IsPrimaryKey = true, PrimaryKeyOrder = 0)] public int     AreaId               { get; set; } // int
		[Column("SEQUENCE"              , IsPrimaryKey = true, PrimaryKeyOrder = 1)] public int     Sequence             { get; set; } // int
		[Column("PROJECTION"                                                      )] public string? Projection           { get; set; } // nvarchar(300)
		[Column("NAME"                                                            )] public string? Name                 { get; set; } // nvarchar(32)
		[Column("TRANSFORMATION_TYPE_ID", IsPrimaryKey = true, PrimaryKeyOrder = 2)] public int     TransformationTypeId { get; set; } // int
	}
}
