// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DMAutoTests
{
	[Table("COORDS_SETTINGS")]
	public class CoordsSetting
	{
		[Column("AREA_ID"                     , IsPrimaryKey = true)] public int     AreaId                     { get; set; } // int
		[Column("ERROR_TRANSFORMATION_EPSILON"                     )] public double? ErrorTransformationEpsilon { get; set; } // float
	}
}
