// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DMAutoTests
{
	[Table("CURRENT_STATE")]
	public class CurrentState
	{
		[Column("UNIT_ID"                 )] public int?      UnitId                { get; set; } // int
		[Column("SYNCHRONIZED"            )] public bool?     Synchronized          { get; set; } // bit
		[Column("STATUS_ID"               )] public int?      StatusId              { get; set; } // int
		[Column("COMPLICATION_ID"         )] public int?      ComplicationId        { get; set; } // int
		[Column("SEG_ID"                  )] public int?      SegId                 { get; set; } // int
		[Column("LOC_ID"                  )] public int?      LocId                 { get; set; } // int
		[Column("DRILL_BLOCK_ID"          )] public int?      DrillBlockId          { get; set; } // int
		[Column("BLAST_BLOCK_ID"          )] public int?      BlastBlockId          { get; set; } // int
		[Column("HOLE_NAME"               )] public string?   HoleName              { get; set; } // nvarchar(32)
		[Column("BLAST_HOLE_NAME"         )] public string?   BlastHoleName         { get; set; } // nvarchar(32)
		[Column("DIG_BLOCK_ID"            )] public int?      DigBlockId            { get; set; } // int
		[Column("DANGER_ZONE_ID"          )] public int?      DangerZoneId          { get; set; } // int
		[Column("HARMFUL_ZONE_ID"         )] public int?      HarmfulZoneId         { get; set; } // int
		[Column("X"                       )] public double?   X                     { get; set; } // float
		[Column("Y"                       )] public double?   Y                     { get; set; } // float
		[Column("Z"                       )] public double?   Z                     { get; set; } // float
		[Column("STAFF_ID"                )] public int?      StaffId               { get; set; } // int
		[Column("PRIMARY_OPERATOR_ID"     )] public int?      PrimaryOperatorId     { get; set; } // int
		[Column("SECONDARY_OPERATOR_ID"   )] public int?      SecondaryOperatorId   { get; set; } // int
		[Column("PARKING_TICKS_COUNT"     )] public double?   ParkingTicksCount     { get; set; } // float
		[Column("START_TICKS_COUNT"       )] public double?   StartTicksCount       { get; set; } // float
		[Column("TICKS_COUNT"             )] public int?      TicksCount            { get; set; } // int
		[Column("START_CHARGE_TOTAL_VALUE")] public int?      StartChargeTotalValue { get; set; } // int
		[Column("INIT_DEFAULT_DATA"       )] public bool?     InitDefaultData       { get; set; } // bit
		[Column("SHIFT_PENETRATION"       )] public double?   ShiftPenetration      { get; set; } // float
		[Column("DATE_PREVIOUS_LAUNCH"    )] public DateTime? DatePreviousLaunch    { get; set; } // datetime
	}
}
