// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DMAutoTests
{
	[Table("CURRENT_STATE_SYNC")]
	public class CurrentStateSync
	{
		[Column("UNIT_ID"       , IsPrimaryKey = true, PrimaryKeyOrder = 1)] public int       UnitId       { get; set; } // int
		[Column("AREA_ID"       , IsPrimaryKey = true, PrimaryKeyOrder = 0)] public int       AreaId       { get; set; } // int
		[Column("LAST_SYNC_TIME"                                          )] public DateTime? LastSyncTime { get; set; } // datetime
	}
}
