// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DMAutoTests
{
	[Table("DRILL_BIT_DIAMETER")]
	public class DrillBitDiameter
	{
		[Column("ID"      , IsPrimaryKey = true)] public int     Id       { get; set; } // int
		[Column("DIAMETER"                     )] public double? Diameter { get; set; } // float
	}
}
