// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DMAutoTests
{
	[Table("DRILL_GAUGE_TRANS")]
	public class DrillGaugeTran
	{
		[Column("ID"            )] public int     Id            { get; set; } // int
		[Column("HOLE_NAME"     )] public string? HoleName      { get; set; } // nvarchar(32)
		[Column("BLOCK_ID"      )] public int?    BlockId       { get; set; } // int
		[Column("DIG_PRESSURE"  )] public double? DigPressure   { get; set; } // float
		[Column("AIR_PRESSURE"  )] public double? AirPressure   { get; set; } // float
		[Column("ROTATION_SPEED")] public double? RotationSpeed { get; set; } // float
		[Column("TORQUE"        )] public double? Torque        { get; set; } // float
		[Column("TIMESTAMP"     )] public string? Timestamp     { get; set; } // nvarchar(50)
		[Column("DEPTH"         )] public double? Depth         { get; set; } // float
		[Column("CURRENT_STATUS")] public string? CurrentStatus { get; set; } // nvarchar(20)
	}
}
