// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DMAutoTests
{
	[Table("DRILL_TRANS")]
	public class DrillTran
	{
		[Column("ID"             )] public int       Id             { get; set; } // int
		[Column("BLOCK_ID"       )] public int?      BlockId        { get; set; } // int
		[Column("HOLE_NAME"      )] public string?   HoleName       { get; set; } // nvarchar(32)
		[Column("START_TIMESTAMP")] public DateTime? StartTimestamp { get; set; } // datetime
		[Column("END_TIMESTAMP"  )] public DateTime? EndTimestamp   { get; set; } // datetime
		[Column("DEPTH"          )] public double?   Depth          { get; set; } // float
	}
}
