// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DMAutoTests
{
	[Table("DRILL_GEO_GAUGE_TYPE")]
	public class DrillGeoGaugeType
	{
		[Column("ID"           , IsPrimaryKey = true)] public int     Id          { get; set; } // int
		[Column("GAUGE_NAME"                        )] public string? GaugeName   { get; set; } // nvarchar(32)
		[Column("ALIAS"                             )] public string? Alias       { get; set; } // nvarchar(32)
		[Column("VALUE_TYPE_ID"                     )] public int?    ValueTypeId { get; set; } // int
		[Column("DESCRIPTION"                       )] public string? Description { get; set; } // nvarchar(128)
		[Column("MAX_VALUE"                         )] public double? MaxValue    { get; set; } // float
	}
}
