// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DMAutoTests
{
	[Table("ENGINE_HOURS")]
	public class EngineHour
	{
		[Column("ID"                , IsPrimaryKey = true)] public int      Id                { get; set; } // int
		[Column("UNIT_ID"                                )] public int      UnitId            { get; set; } // int
		[Column("ENGINE_HOURS"                           )] public double   EngineHours       { get; set; } // float
		[Column("MODIFIED_TIMESTAMP"                     )] public DateTime ModifiedTimestamp { get; set; } // datetime
	}
}
