// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DMAutoTests
{
	[Table("EXPLOSIVE_TANK")]
	public class ExplosiveTank
	{
		[Column("UNIT_ID"               , IsPrimaryKey = true)] public int       UnitId              { get; set; } // int
		[Column("TANK_EXPLOSIVE_WEIGHT"                      )] public double?   TankExplosiveWeight { get; set; } // float
		[Column("SUM_EXPLOSIVE_ON_SHIFT"                     )] public double?   SumExplosiveOnShift { get; set; } // float
		[Column("UPDATE_DATE"                                )] public DateTime? UpdateDate          { get; set; } // datetime
	}
}
