// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DMAutoTests
{
	[Table("FUEL_TRANS")]
	public class FuelTran
	{
		[Column("TIMESTAMP"                 , IsPrimaryKey = true, PrimaryKeyOrder = 0)] public DateTime  Timestamp               { get; set; } // datetime
		[Column("TIMESTAMP_SHIFT_ID"                                                  )] public int?      TimestampShiftId        { get; set; } // int
		[Column("TIMESTAMP_SHIFT_DATE"                                                )] public DateTime? TimestampShiftDate      { get; set; } // datetime
		[Column("CURRENT_FUEL_LEVEL"                                                  )] public double    CurrentFuelLevel        { get; set; } // float
		[Column("UNIT_ID"                   , IsPrimaryKey = true, PrimaryKeyOrder = 1)] public int       UnitId                  { get; set; } // int
		[Column("SPEED"                                                               )] public double    Speed                   { get; set; } // float
		[Column("PERCENT_CURRENT_FUEL_LEVEL"                                          )] public double    PercentCurrentFuelLevel { get; set; } // float
	}
}
