// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DMAutoTests
{
	[Table("HISTORY_REPEATER")]
	public class HistoryRepeater
	{
		[Column("ID"           )] public int?      Id           { get; set; } // int
		[Column("ARCHIVE_NAME" )] public string?   ArchiveName  { get; set; } // nvarchar(32)
		[Column("TIMESTAMP"    )] public DateTime? Timestamp    { get; set; } // datetime
		[Column("REPEATER_NAME")] public string?   RepeaterName { get; set; } // nvarchar(32)
	}
}
