// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DMAutoTests
{
	[Table("HP_JOB")]
	public class HpJob
	{
		[Column("ID"             , IsPrimaryKey = true)] public int       Id             { get; set; } // int
		[Column("NAME"                                )] public string?   Name           { get; set; } // nvarchar(32)
		[Column("DRILL_BLOCK_ID"                      )] public int?      DrillBlockId   { get; set; } // int
		[Column("DIG_BLOCK_ID"                        )] public int?      DigBlockId     { get; set; } // int
		[Column("LAYER_ID"                            )] public int?      LayerId        { get; set; } // int
		[Column("BLAST_BLOCK_ID"                      )] public int?      BlastBlockId   { get; set; } // int
		[Column("START_TIMESTAMP"                     )] public DateTime? StartTimestamp { get; set; } // datetime
		[Column("ACTIVE"                              )] public bool?     Active         { get; set; } // bit
		[Column("AREA_ID"                             )] public int?      AreaId         { get; set; } // int
	}
}
