// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DMAutoTests
{
	[Table("LOCATION_BEACON")]
	public class LocationBeacon
	{
		[Column("ID"    )] public int? Id    { get; set; } // int
		[Column("LOC_ID")] public int? LocId { get; set; } // int
		[Column("SEG_ID")] public int? SegId { get; set; } // int
	}
}
