// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DMAutoTests
{
	[Table("LOCATION")]
	public class Location
	{
		[Column("ID"          )] public int?    Id          { get; set; } // int
		[Column("NAME"        )] public string? Name        { get; set; } // nvarchar(32)
		[Column("TYPE_ID"     )] public int?    TypeId      { get; set; } // int
		[Column("AREA_ID"     )] public int?    AreaId      { get; set; } // int
		[Column("BUILDING_ID" )] public int?    BuildingId  { get; set; } // int
		[Column("FLOOR_NUMBER")] public int?    FloorNumber { get; set; } // int
		[Column("HIGH_MARK"   )] public string? HighMark    { get; set; } // nvarchar(16)
		[Column("ACTIVE"      )] public bool?   Active      { get; set; } // bit
	}
}
