// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DMAutoTests
{
	[Table("LOCATION_POINT")]
	public class LocationPoint
	{
		[Column("LOC_ID"       )] public int?      LocId        { get; set; } // int
		[Column("SEQUENCE"     )] public byte?     Sequence     { get; set; } // tinyint
		[Column("X"            )] public double?   X            { get; set; } // float
		[Column("Y"            )] public double?   Y            { get; set; } // float
		[Column("Z"            )] public double?   Z            { get; set; } // float
		[Column("END_TIMESTAMP")] public DateTime? EndTimestamp { get; set; } // datetime
	}
}
