// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DMAutoTests
{
	[Table("MAINTENANCE")]
	public class Maintenance
	{
		[Column("ID"                 , IsPrimaryKey = true)] public int     Id                { get; set; } // int
		[Column("NAME"                                    )] public string? Name              { get; set; } // nvarchar(2000)
		[Column("STATUS_ID"                               )] public int?    StatusId          { get; set; } // int
		[Column("ENGINE_HOURS_PERIOD"                     )] public int?    EngineHoursPeriod { get; set; } // int
		[Column("ACTIVE"                                  )] public bool?   Active            { get; set; } // bit
	}
}
