// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DMAutoTests
{
	[Table("MATERIAL")]
	public class Material
	{
		[Column("ID"         , IsPrimaryKey = true)] public int     Id         { get; set; } // int
		[Column("NAME"                            )] public string? Name       { get; set; } // nvarchar(32)
		[Column("TYPE_ID"                         )] public int?    TypeId     { get; set; } // int
		[Column("UNIT_WEIGHT"                     )] public double? UnitWeight { get; set; } // float
		[Column("UOM_ID"                          )] public int?    UomId      { get; set; } // int
		[Column("COLOR"                           )] public int?    Color      { get; set; } // int
		[Column("ACTIVE"                          )] public bool?   Active     { get; set; } // bit
	}
}
