// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DMAutoTests
{
	[Table("RFID_CARD")]
	public class RfidCard
	{
		[Column("ID"             )] public int?     Id             { get; set; } // int
		[Column("CARD_IDENTIFIER")] public decimal? CardIdentifier { get; set; } // numeric(8, 5)
		[Column("ACTIVE"         )] public bool?    Active         { get; set; } // bit
	}
}
