// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DMAutoTests
{
	[Table("SEGMENT_POINT")]
	public class SegmentPoint
	{
		[Column("ID"        )] public int?    Id        { get; set; } // int
		[Column("SEGMENT_ID")] public int?    SegmentId { get; set; } // int
		[Column("X"         )] public double? X         { get; set; } // float
		[Column("Y"         )] public double? Y         { get; set; } // float
		[Column("Z"         )] public double? Z         { get; set; } // float
		[Column("SEQUENCE"  )] public byte?   Sequence  { get; set; } // tinyint
	}
}
