// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DMAutoTests
{
	[Table("SHIFT")]
	public class Shift
	{
		[Column("ID"        , IsPrimaryKey = true)] public int       Id        { get; set; } // int
		[Column("SEQUENCE"                       )] public byte?     Sequence  { get; set; } // tinyint
		[Column("START_TIME"                     )] public DateTime? StartTime { get; set; } // datetime
		[Column("END_TIME"                       )] public DateTime? EndTime   { get; set; } // datetime
		[Column("NAME"                           )] public string?   Name      { get; set; } // nvarchar(32)
		[Column("ACTIVE"                         )] public bool?     Active    { get; set; } // bit
	}
}
