// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System.Collections.Generic;
using System.Windows.Documents;
using System.Linq;

#pragma warning disable 1573, 1591
#nullable enable

namespace DMAutoTests
{
	[Table("STAFF_MOBILE")]
	public class StaffMobile
	{
		[Column("ID"                , IsPrimaryKey = true)] public int     Id               { get; set; } // int
		[Column("NAME"                                   )] public string? Name             { get; set; } // nvarchar(32)
		[Column("SURNAME"                                )] public string? Surname          { get; set; } // nvarchar(32)
		[Column("PATRONYMIC"                             )] public string? Patronymic       { get; set; } // nvarchar(32)
		[Column("NUMBER"                                 )] public string? Number           { get; set; } // nvarchar(6)
		[Column("PASSWORD"                               )] public string? Password         { get; set; } // nvarchar(32)
		[Column("TYPE_ID"                                )] public int?    TypeId           { get; set; } // int
		[Column("AREA_ID"                                )] public int?    AreaId           { get; set; } // int
		[Column("CREW_ID"                                )] public int?    CrewId           { get; set; } // int
		[Column("RANK_ID"                                )] public int?    RankId           { get; set; } // int
		[Column("GRADE_ID"                               )] public int?    GradeId          { get; set; } // int
		[Column("MULTIPLE_AREAS"                         )] public bool?   MultipleAreas    { get; set; } // bit
		[Column("ID_CARD_IDENTIFIER"                     )] public int?    IdCardIdentifier { get; set; } // int
		[Column("ACTIVE"                                 )] public bool?   Active           { get; set; } // bit

		public static List<StaffMobile> GetAllData()
		{
			using (RitNewdb db = new RitNewdb("RIT_NEW"))
			{
				return (from sm in db.StaffMobiles select sm).ToList();
			}
		}
	}
}
