// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;
using System;

#pragma warning disable 1573, 1591
#nullable enable

namespace DMAutoTests
{
	[Table("STAFF_OFFICE")]
	public class StaffOffice
	{
		[Column("ID"               )] public int?      Id              { get; set; } // int
		[Column("NAME"             )] public string?   Name            { get; set; } // nvarchar(32)
		[Column("SID"              )] public string?   Sid             { get; set; } // nvarchar(64)
		[Column("ROLE_ID"          )] public int?      RoleId          { get; set; } // int
		[Column("DATE_HIRED"       )] public DateTime? DateHired       { get; set; } // datetime
		[Column("DATE_LEFT_COMPANY")] public DateTime? DateLeftCompany { get; set; } // datetime
		[Column("ACTIVE"           )] public bool?     Active          { get; set; } // bit
		[Column("PASSWORD"         )] public string?   Password        { get; set; } // nvarchar(50)
		[Column("EMAIL"            )] public string?   Email           { get; set; } // nvarchar(50)
	}
}
