// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DMAutoTests
{
	[Table("SYSTEM_CONFIG")]
	public class SystemConfig
	{
		[Column("ID"                                 , IsPrimaryKey = true)] public int     Id                             { get; set; } // int
		[Column("COORDS_WRITE_INTERVAL"                                   )] public short?  CoordsWriteInterval            { get; set; } // smallint
		[Column("TRUCK_WEIGHT_SHORTAGE_RATIO"                             )] public short?  TruckWeightShortageRatio       { get; set; } // smallint
		[Column("TRUCK_WEIGHT_EXCESS_RATIO"                               )] public short?  TruckWeightExcessRatio         { get; set; } // smallint
		[Column("WIFI_PREFERRED_NETWORK"                                  )] public bool?   WifiPreferredNetwork           { get; set; } // bit
		[Column("AUTO_TRUCK_REBIND"                                       )] public bool?   AutoTruckRebind                { get; set; } // bit
		[Column("VIRTUAL_UNIT_DELAY"                                      )] public short?  VirtualUnitDelay               { get; set; } // smallint
		[Column("COORDS_WRITE_INTERVAL_DRILL_DRILL"                       )] public short?  CoordsWriteIntervalDrillDrill  { get; set; } // smallint
		[Column("COORDS_WRITE_INTERVAL_DRILL_MOVE"                        )] public short?  CoordsWriteIntervalDrillMove   { get; set; } // smallint
		[Column("ADMIN_PASSWORD"                                          )] public string? AdminPassword                  { get; set; } // nvarchar(16)
		[Column("HOLE_PICK_RADIUS"                                        )] public double? HolePickRadius                 { get; set; } // float
		[Column("INTERVAL_SENSORS"                                        )] public double? IntervalSensors                { get; set; } // float
		[Column("MEMU_JOB_AUTO_ASSIGN"                                    )] public bool?   MemuJobAutoAssign              { get; set; } // bit
		[Column("TIME_OF_DEACTIVATION_BLOCKS"                             )] public string? TimeOfDeactivationBlocks       { get; set; } // nvarchar(32)
		[Column("CHARGE_THRESHOLD"                                        )] public string? ChargeThreshold                { get; set; } // nvarchar(32)
		[Column("AUTO_IMPORT_INTERVAL"                                    )] public int?    AutoImportInterval             { get; set; } // int
		[Column("RAW_GAUGES_WRITE_INTERVAL"                               )] public int?    RawGaugesWriteInterval         { get; set; } // int
		[Column("FULL_TELEMETRY_SKIP_EMPTY_ROW_COUNT"                     )] public int?    FullTelemetrySkipEmptyRowCount { get; set; } // int
		[Column("WIALON_FUEL_IP"                                          )] public string? WialonFuelIp                   { get; set; } // nvarchar(32)
		[Column("WIALON_FUEL_PORT"                                        )] public int?    WialonFuelPort                 { get; set; } // int
		[Column("WIALON_FUEL_ENABLED"                                     )] public bool?   WialonFuelEnabled              { get; set; } // bit
		[Column("FUEL_WIALON_FIELD_NAME"                                  )] public string? FuelWialonFieldName            { get; set; } // nvarchar(64)
	}
}
