// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DMAutoTests
{
	[Table("TABLE_VERSION")]
	public class TableVersion
	{
		[Column("ID"        )] public int?    Id        { get; set; } // int
		[Column("TABLE_NAME")] public string? TableName { get; set; } // nvarchar(32)
		[Column("VERSION"   )] public int?    Version   { get; set; } // int
	}
}
