// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DMAutoTests
{
	[Table("UNIT_STATUS")]
	public class UnitStatus
	{
		[Column("ID"             , IsPrimaryKey = true)] public int     Id             { get; set; } // int
		[Column("NAME"                                )] public string? Name           { get; set; } // nvarchar(32)
		[Column("COLOR"                               )] public int?    Color          { get; set; } // int
		[Column("CAT_ID"                              )] public int?    CatId          { get; set; } // int
		[Column("LATE_TIME"                           )] public int?    LateTime       { get; set; } // int
		[Column("STANDARD_TIME"                       )] public int?    StandardTime   { get; set; } // int
		[Column("COMPLICATION_ID"                     )] public int?    ComplicationId { get; set; } // int
		[Column("VERY_LATE_TIME"                      )] public int?    VeryLateTime   { get; set; } // int
		[Column("ALIAS"                               )] public string? Alias          { get; set; } // nvarchar(8)
		[Column("ACTIVE"                              )] public bool?   Active         { get; set; } // bit
		[Column("AUTO"                                )] public bool?   Auto           { get; set; } // bit
	}
}
