// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DMAutoTests
{
	[Table("UNIT")]
	public class Unit
	{
		[Column("ID"           , IsPrimaryKey = true)] public int     Id           { get; set; } // int
		[Column("NAME"                              )] public string? Name         { get; set; } // nvarchar(32)
		[Column("SERIAL_NUMBER"                     )] public string? SerialNumber { get; set; } // nvarchar(32)
		[Column("AREA_ID"                           )] public int?    AreaId       { get; set; } // int
		[Column("TYPE_ID"                           )] public int?    TypeId       { get; set; } // int
		[Column("GROUP_ID"                          )] public int?    GroupId      { get; set; } // int
		[Column("MODEL_ID"                          )] public int?    ModelId      { get; set; } // int
		[Column("PROFILE_ID"                        )] public int?    ProfileId    { get; set; } // int
		[Column("CAM_LAYOUT_ID"                     )] public int?    CamLayoutId  { get; set; } // int
		[Column("SOFT_TYPE_ID"                      )] public byte?   SoftTypeId   { get; set; } // tinyint
		[Column("MU_VERSION"                        )] public string? MuVersion    { get; set; } // nvarchar(16)
		[Column("IP_ADDRESS"                        )] public bool?   IpAddress    { get; set; } // bit
		[Column("PORT"                              )] public short?  Port         { get; set; } // smallint
		[Column("CAMANAGER"                         )] public bool?   Camanager    { get; set; } // bit
		[Column("ACTIVE"                            )] public bool?   Active       { get; set; } // bit
		[Column("WIALON_ID"                         )] public string? WialonId     { get; set; } // nvarchar(32)
		[Column("AUTOSTATUS"                        )] public bool?   Autostatus   { get; set; } // bit
	}
}
