// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DMAutoTests
{
	[Table("UNIT_SHOVEL")]
	public class UnitShovel
	{
		[Column("UNIT_ID"         )] public int?    UnitId         { get; set; } // int
		[Column("LOAD_RADIUS"     )] public double? LoadRadius     { get; set; } // float
		[Column("WAIT_LOAD_RADIUS")] public double? WaitLoadRadius { get; set; } // float
		[Column("MATERIAL_ID"     )] public int?    MaterialId     { get; set; } // int
	}
}
