// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DMAutoTests
{
	[Table("UNIT_DRILL")]
	public class UnitDrill
	{
		[Column("UNIT_ID"       , IsPrimaryKey = true)] public int     UnitId        { get; set; } // int
		[Column("HIGH_PRECISION"                     )] public bool?   HighPrecision { get; set; } // bit
		[Column("WIDTH"                              )] public double? Width         { get; set; } // float
		[Column("LENGTH"                             )] public double? Length        { get; set; } // float
		[Column("ROD_LENGTH"                         )] public double? RodLength     { get; set; } // float
		[Column("ROD_DIAMETER"                       )] public double? RodDiameter   { get; set; } // float
		[Column("DEPTH_FACTOR"                       )] public double? DepthFactor   { get; set; } // float
		[Column("DRILL_TYPE_ID"                      )] public int?    DrillTypeId   { get; set; } // int
	}
}
