// ---------------------------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by LinqToDB scaffolding tool (https://github.com/linq2db/linq2db).
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ---------------------------------------------------------------------------------------------------

using LinqToDB.Mapping;

#pragma warning disable 1573, 1591
#nullable enable

namespace DMAutoTests
{
	[Table("VIRTUAL_GEO_PLC_TEMP_PARAMS")]
	public class VirtualGeoPlcTempParam
	{
		[Column("ID"                                             )] public int     Id                        { get; set; } // int
		[Column("HOLE_NAME"                   , CanBeNull = false)] public string  HoleName                  { get; set; } = null!; // nvarchar(32)
		[Column("CASING_DEPTH"                                   )] public double? CasingDepth               { get; set; } // float
		[Column("COUNT_RODS_CASING"                              )] public int?    CountRodsCasing           { get; set; } // int
		[Column("COUNT_RODS_DRILLING"                            )] public int?    CountRodsDrilling         { get; set; } // int
		[Column("COUNT_RODS_CASING_PREVIOUS"                     )] public int?    CountRodsCasingPrevious   { get; set; } // int
		[Column("COUNT_RODS_DRILLING_PREVIOUS"                   )] public int?    CountRodsDrillingPrevious { get; set; } // int
		[Column("DEPTH_SSK"                                      )] public double? DepthSsk                  { get; set; } // float
		[Column("OPERATIVE_MEASURE"                              )] public double? OperativeMeasure          { get; set; } // float
		[Column("DEAD_MEASURE"                                   )] public double? DeadMeasure               { get; set; } // float
	}
}
